services:
  app:
    image: phonebook-frontend-prod
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app
    container_name: phonebook-app-frontend-prod
    depends_on:
      - server
  server:
    image: phonebook-backend-prod
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - ./server/:/usr/src/app
    container_name: phonebook-app-backend-prod
    env_file:
      - ./server/.env
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: phonebook-reverse-proxy-prod
    depends_on:
      - app
      - server
  debug-helper:
    image: busybox